/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bilalcode_wifipc_api_external_Scan */

#ifndef _Included_com_bilalcode_wifipc_api_external_Scan
#define _Included_com_bilalcode_wifipc_api_external_Scan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bilalcode_wifipc_api_external_Scan
 * Method:    newScan
 * Signature: ()Lcom/bilalcode/wifipc/WpcScan;
 */
JNIEXPORT jobject JNICALL Java_com_bilalcode_wifipc_api_external_Scan_newScan
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
