/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bilalcode_wifipc_api_external_NativeScan */

#ifndef _Included_com_bilalcode_wifipc_api_external_NativeScan
#define _Included_com_bilalcode_wifipc_api_external_NativeScan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bilalcode_wifipc_api_external_NativeScan
 * Method:    newScan
 * Signature: ()Lcom/bilalcode/wifipc/api/external/record/NativeScanResult;
 */
JNIEXPORT jobject JNICALL Java_com_bilalcode_wifipc_api_external_NativeScan_newScan
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
